// Generated by CoffeeScript 1.12.4
(function() {
  var grammar, nearley, parser;

  nearley = require('./nearley');

  grammar = require('./grammar');

  parser = new nearley.Parser(grammar.ParserRules, grammar.ParserStart);

  parser.feed("x");

  console.log(parser.results);

}).call(this);

//# sourceMappingURL=playground.js.map
